[package]
name = "cant"
version = "0.0.3"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "ECS"
authors = ["Ivan Chetchasov <vi.is.chapmann@gmail.com>"]
repository = "https://github.com/ursetek/cant"
rust-version = "1.98.1"
workspace = "workspace"

[dependencies]
rayon = "1"
rustc-hash = "2"
cant-macros = { version = "0.0.2", path = "cant-macros" }

[profile.release]
lto = "fat"
codegen-units = 1
strip = true

[lints]
rust.missing_docs = "deny"
clippy.all = "warn"
clippy.pedantic = "warn"

[dev-dependencies]
trybuild = "1"
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "spawn"
harness = false

[[bench]]
name = "query"
harness = false

[[bench]]
name = "migration"
harness = false

[[bench]]
name = "schedule"
harness = false

[[bench]]
name = "projection"
harness = false
